name: Build Image

on:
  pull_request:
    branches:
      - main
    paths:
      # '*' matches any character except '/'
      - 'image/*'
      - '.github/workflows/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build Imag:aws-cli
        run: |
          cd images
          IMAGE_NAME=ringcentral/aws-cli
          docker build -t ${IMAGE_NAME} -f Dockerfile.aws-cli .
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:latest"
      - name: Build Imag:gsuite-cli
        run: |
          cd images
          IMAGE_NAME=ringcentral/gsuite-cli
          docker build -t ${IMAGE_NAME} -f Dockerfile.gsuite-cli .
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:latest"